skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pumpfantasy = "4sLvdTFMxJbewJS7gNF6KeqDdkRd12syav8veM4AuYRu"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
